--- #loops playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: add list of users
            action: user name='{{item}}' state=present
            with_items:
                    - gaurav
                    - kumar
                    - love

